MPCcontroller:
  timeSteps: 12
  sampleTime: 0.1

  reference:
    velocity: 2
    crossTrackError: 0
    orientationError: 0

  maxBounds:
    maxOmega: 3.0
    maxThrottle: 5.0

  weights:
    w_cte: 3000
    w_etheta: 3000
    w_vel: 1500
    w_omega: 5
    w_acc: 5
    w_omega_d: 10
    w_acc_d: 500
